// api status
const NOT_FOUND = "NOT_FOUND"
const BAD_REQUEST = "BAD_REQUEST"
const FORBIDDEN = "FORBIDDEN"
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
const UNAUTHORIZED = "UNAUTHORIZED"

// api response
const FIELDS_MISSING = "FIELDS_MISSING"
const PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
const USER_CREATED = "USER_CREATED"
const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"
const INSTITUTE_CREATED = "INSTITUTE_CREATED"
const INSTITUTE_NOT_FOUND = "INSTITUTE_NOT_FOUND"
const INSTITUTE_LOGGED_IN = "INSTITUTE_LOGGED_IN"
const INSTITUTE_ALREADY_EXISTS = "INSTITUTE_ALREADY_EXISTS"
const INSTITUTE_DATA_UPDATED = "INSTITUTE_DATA_UPDATED"
const PASSWORD_RESET_CODE_SEND = "PASSWORD_RESET_CODE_SEND"
const INVALID_RESET_CODE = "INVALID_RESET_CODE"
const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"
const INVALID_SESSION = "INVALID_SESSION"
const TOKEN_MISSING = "TOKEN_MISSING"
const TOKEN_EXPIRED = "TOKEN_EXPIRED"
const TEACHERS_LIST_NOT_FOUND = "TEACHERS_LIST_NOT_FOUND"
const TEACHERS_NOT_FOUND = "TEACHERS_NOT_FOUND"
const TEACHERS_ADDED_SUCCESSFULLY = "TEACHERS_ADDED_SUCCESSFULLY"
const TEACHERS_UPDATED_SUCCESSFULLY = "TEACHERS_UPDATED_SUCCESSFULLY"
const TEACHERS_RETRIEVED_SUCCESSFULLY = "TEACHERS_RETRIEVED_SUCCESSFULLY"
const TEACHERS_DELETED_SUCCESSFULLY = "TEACHERS_DELETED_SUCCESSFULLY"
const DUPLICATE_EMAILS_FOUND = "DUPLICATE_EMAILS_FOUND"
const TEACHERS_LOGGED_IN = "TEACHERS_LOGGED_IN"
const TEACHER_NOT_ACTIVATED = "TEACHER_NOT_ACTIVATED"
const TEACHER_ACTIVATED = "TEACHER_ACTIVATED"
const TEACHER_ALREADY_ACTIVATED = "TEACHER_ALREADY_ACTIVATED"

module.exports = {
    NOT_FOUND,
    BAD_REQUEST,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    FIELDS_MISSING,
    PASSWORDS_DO_NOT_MATCH,
    USER_ALREADY_EXISTS,
    USER_CREATED,
    SOMETHING_WENT_WRONG,
    INSTITUTE_NOT_FOUND,
    INCORRECT_PASSWORD,
    INSTITUTE_LOGGED_IN,
    INSTITUTE_DATA_UPDATED,
    PASSWORD_RESET_CODE_SEND,
    INVALID_RESET_CODE,
    PASSWORD_RESET_SUCCESS,
    INVALID_SESSION,
    TOKEN_MISSING,
    TOKEN_EXPIRED,
    TEACHERS_LIST_NOT_FOUND,
    TEACHERS_ADDED_SUCCESSFULLY,
    TEACHERS_RETRIEVED_SUCCESSFULLY,
    TEACHERS_NOT_FOUND,
    TEACHERS_UPDATED_SUCCESSFULLY,
    TEACHERS_DELETED_SUCCESSFULLY,
    INSTITUTE_CREATED,
    INSTITUTE_ALREADY_EXISTS,
    DUPLICATE_EMAILS_FOUND,
    TEACHERS_LOGGED_IN,
    TEACHER_NOT_ACTIVATED,
    TEACHER_ACTIVATED,
    TEACHER_ALREADY_ACTIVATED
}