// api status
const NOT_FOUND = "NOT_FOUND"
const BAD_REQUEST = "BAD_REQUEST"
const FORBIDDEN = "FORBIDDEN"
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
const UNAUTHORIZED = "UNAUTHORIZED"

// api response
const FIELDS_MISSING = "FIELDS_MISSING"
const PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
const USER_CREATED = "USER_CREATED"
const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"

module.exports = {
    NOT_FOUND,
    BAD_REQUEST,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    FIELDS_MISSING,
    PASSWORDS_DO_NOT_MATCH,
    USER_ALREADY_EXISTS,
    USER_CREATED,
    SOMETHING_WENT_WRONG
}